VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsFileOperation"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function isFileExists(pathfileName As String, Optional errMsg As String = "", Optional enableLog As Boolean = False) As Boolean

End Function


Public Function copyFile(fromPath As String, fileName As String, toPath As String, Optional toName As String = "", Optional errMsg As String = "", Optional enableLog As Boolean = False)

End Function

Public Function moveFile()


End Function


Public Function renameFile()

End Function


Public Function makeDirectory()

End Function

Public Function compareFile()


End Function

